### ISSUE TITLE
Won't compile with recent versions of Java 8

### ISSUE THREAD

**Issue by paulk-asert** [nurkiewicz/LazySeq#1]
I tried building using Maven 3 and Java 8 b104. It looks like changes have been made in the Java 8 API. For example the interface `Collector<T, A, R>` has three type arguments but the `LazySeq` code base seems to expect only 2. Similarly there are 11 other errors when I try to build. Many look closely related to the above change. I could try to do a pull request but it will be some weeks before I have time to get back to it.

**Comment by nurkiewicz** [comment]
You are right, JDK 8 changed in the meantime. I will take care of this, thanks for reporting!

**Comment by nurkiewicz** [comment]
Fixed in #2 by @SamirTalwar. Now runs successfully on top of JDK 8 build 113.
